blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/guruCodeJourney/gemini-pro-chat/discussions
    about: Use discussions if you have an idea for improvement or for asking questions.